name: Client CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Install smart_contract dependencies
        run: npm install
        working-directory: smart_contract

      - name: Build contract artifacts
        run: npx hardhat compile
        working-directory: smart_contract

      - name: Run unit tests
        run: npm test -- --watchAll=false
        working-directory: client
