name: Upload Test Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Install smart_contract dependencies
        run: npm install
        working-directory: smart_contract

      - name: Build contract artifacts
        run: npx hardhat compile
        working-directory: smart_contract

      - name: Run unit tests
        run: npm test -- --coverage --watchAll=false
        working-directory: client

      - name: Run code coverage for smart contract side
        run: npx hardhat coverage
        working-directory: smart_contract

      # Upload test code coverage to CodeClimate (this also uploads smart contract side's test coverage)
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 914f6eb49f22f433dee5c420ccaeedf35b7d4861b9b18e25d7f96dd7bd565bc8
        with:
          coverageLocations: |
            ${{github.workspace}}/client/coverage/lcov.info:lcov
            ${{github.workspace}}/smart_contract/coverage/lcov.info:lcov
