name: Smart Contracts CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: smart_contract/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: smart_contract
      
      - name: Run unit tests
        run: npx hardhat coverage
        working-directory: smart_contract

      # Upload test code coverage to CodeClimate
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 914f6eb49f22f433dee5c420ccaeedf35b7d4861b9b18e25d7f96dd7bd565bc8
        with:
          coverageLocations: |
            ${{github.workspace}}/smart_contract/coverage/lcov.info:lcov
